
create table PERSISTENT_EVENT(
    ID BIGINT(19) AUTO_INCREMENT NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    VERSION_NO INTEGER(10) NOT NULL,
    PRIMARY KEY (ID)
);

create table PERSISTENT_EVENT_VALUE(
    ID BIGINT(19) AUTO_INCREMENT NOT NULL,
    EVENT_ID BIGINT(19) NOT NULL,
    NAME VARCHAR(4000) NOT NULL,
    VALUE VARCHAR(4000) NOT NULL,
    CLASS_TYPE VARCHAR(255) NOT NULL,
    VERSION_NO INTEGER(10) NOT NULL,
    PRIMARY KEY (ID)
);

alter table PERSISTENT_EVENT_VALUE add constraint FK_PERSISTENT_EVENT_VALUE_PERSISTENT_EVENT
    foreign key (EVENT_ID) references PERSISTENT_EVENT (ID);
